use_frameworks!

target 'SendBirdCombine_Example' do
  pod 'SendBirdCombine', :path => '../'

  target 'SendBirdCombine_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
